development: &global_settings
  database: <%= file_name %>_development
  host: 127.0.0.1
  port: 27017

test:
  database: <%= file_name %>_test
  <<: *global_settings

production:
  host: hostname
  database: <%= file_name %>_production
  username: username
  password: password
  <<: *global_settings
